version: '3'
services:
  mariadb:
    image: 'mariadb:10.7-focal'
    container_name: laravel_mariadb
    # ports:
    #   - '3306:${DB_PORT:-3306}'
    environment:
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD:-password}'
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'mariadb:/var/lib/mysql'

  laravel:
    build: .
    container_name: laravel_app
    working_dir: /root/app
    ports:
      - 8000:8000
    volumes:
      - ./:/root/app
      - ~/.ssh/:/root/.ssh/
    depends_on:
      - mariadb
volumes:
  mariadb:
    driver: local
